<a href="https://colab.research.google.com/github/eormeno12/CursoIntroduccionAlML/blob/2.Trabajando_con_Pytorch/2_Trabajando_con_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np
import pandas as pd

#Introducción a PyTorch

####Funciones básicas


In [ ]:
torch.__version__

'1.6.0+cu101'

Un tensor se crea con la función **Tensor** a la cual se le asigna el shape de este.

La función **uniform** hace que los datos del tensor solo puedan poseer valores entre los números dados.

In [ ]:
Tensor = torch.Tensor(4, 2)
print(Tensor)
print(Tensor.uniform_(-10, 1))

tensor([[1.5135e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 5.6052e-44],
        [4.4721e+21, 1.5956e+25]])
tensor([[-5.5140, -8.1703],
        [-5.8267, -7.7228],
        [-3.3942, -4.3007],
        [-1.1057, -5.9342]])


La función **rand** genera un vector cuyos datos varían de 0 a 1, a esta función se le pasa el shape del vector deseado.

In [ ]:
tensor_rand = torch.rand(4, 2)
tensor_rand

tensor([[0.1423, 0.0158],
        [0.5382, 0.6409],
        [0.0219, 0.9415],
        [0.2157, 0.9939]])

####Suma de vectores

Solo se puede efectuar una suma si los vectores tienen el mismo shape o dimensión, está se da sumando los datos que se encuentran en la misma posición.

In [ ]:
result = Tensor + tensor_rand
print(result)

tensor([[-5.3717, -8.1545],
        [-5.2885, -7.0819],
        [-3.3722, -3.3592],
        [-0.8899, -4.9403]])


El vector resultante tendrá como shape o dimensión que los vectores sumados.

Con la función **view** podemos hacer un reshape del vector. En este caso se traba de un 4x2 y lo convertimos a un 2x4.

In [ ]:
result.shape
reshaped = result.view(2, 4)
reshaped

tensor([[-5.3717, -8.1545, -5.2885, -7.0819],
        [-3.3722, -3.3592, -0.8899, -4.9403]])

####Más funciones con tensores

Con la función **storage** podemos visualizar los datos de un tensor como si se tratara de un array de dimensión 1.

In [ ]:
points = torch.tensor([[2.0, 1.0], [5.0, 4.5], [3.0, 10.0]])
print(points)
print(points.storage())

tensor([[ 2.0000,  1.0000],
        [ 5.0000,  4.5000],
        [ 3.0000, 10.0000]])
 2.0
 1.0
 5.0
 4.5
 3.0
 10.0
[torch.FloatStorage of size 6]


La función **stride**, en español "paso", nos da como resultado el shape necesario para encontrar el siguiente elemento dentro del tensor.

In [ ]:
print(points.t())
points.stride()

tensor([[ 2.0000,  5.0000,  3.0000],
        [ 1.0000,  4.5000, 10.0000]])


(2, 1)

La función **unsqueeze** retorna el tensor input como un ouput que cumple con la dimensión especificada al momento de aplicar la función.

In [ ]:
tensor = torch.tensor([[2.0, 1.0], [5.0, 4.5], [3.0, 10.0]])
print(tensor)
torch.unsqueeze(tensor, 1)

tensor([[ 2.0000,  1.0000],
        [ 5.0000,  4.5000],
        [ 3.0000, 10.0000]])


tensor([[[ 2.0000,  1.0000]],

        [[ 5.0000,  4.5000]],

        [[ 3.0000, 10.0000]]])

La funciñon **from_numpy** nos permite generar un tensor a partir de un array previamente creado por la librearía numpy.

In [ ]:
numpArray = np.random.randn(100, 10000)
np_tensor = torch.from_numpy(numpArray)
np_tensor

tensor([[ 0.3003, -1.1346,  0.3366,  ...,  1.3618,  1.5733, -0.4061],
        [-0.6307, -0.9019,  0.5218,  ..., -1.1627,  0.6662, -0.0084],
        [ 0.1156,  1.3440,  0.3007,  ...,  0.8856, -2.8968, -0.4303],
        ...,
        [-0.3459,  1.9311, -0.8987,  ...,  1.6781, -0.7088, -0.9361],
        [-1.7345, -0.5108,  0.5668,  ..., -1.2273,  0.2610,  1.8531],
        [-1.3855, -0.5571, -0.5249,  ..., -1.6367, -1.5753,  1.2465]],
       dtype=torch.float64)

#Datos con Tensores

####Promedio y Desviación Estándar

La función **mean** retorna el promedio de los datos que se encuentran en la dimensión especificada.

In [7]:
tensor_prueba = torch.Tensor([[1, 5],[1, 6],[1, 5]])
mean = tensor_prueba.mean(dim=1)
mean

tensor([3.0000, 3.5000, 3.0000])

La función **std** retorna la desviación estándar de los datos que se encuentran en la dimensión especificada.

In [ ]:
torch.std(tensor_prueba, dim=0)

tensor([0.0000, 0.5774])

####Guardar Tensores

Con **save** pasamos el tensor a guardar y definimos su nombre.

**Importante**: Colocar el sufijo ".t" cuando se trata de un tensor.

In [ ]:
torch.save(tensor_prueba, "tensorprueba.t")

Podemos cargar el tensor mediante la función **load** y colocando el nombre del mismo.

In [ ]:
load = torch.load("tensorprueba.t")
load

tensor([[1., 5.],
        [1., 6.],
        [1., 5.]])

####Ejemplo de manipulación de Tensores para representar datos

Con la librería panda podemos extraer el dataframe de un url utilizando la función **read_csv** si se trata de ese tipo de archivo.

In [ ]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

#####Propiedades/Funciones de un dataframe

**Colums** retorna el nombre de cada columna del dataframe.

In [ ]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

**Count** retorna el shape del dataframe.

In [ ]:
dataframe.count

<bound method DataFrame.count of        Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]>

Creación de un subset/tensor para poder visualizar solo la data que deseamos.

In [ ]:
subset = dataframe[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0, how="any")
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type

(torch.Size([18159, 5]), <function Tensor.type>)

In [ ]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [ ]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [ ]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [ ]:
sigma = torch.std(data, dim=0)

Hallando la **distribución normal** mediante el mean y el std.



In [ ]:
des_norm = (data - mean) / torch.sqrt(sigma)
des_norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

Dividiendo la data mediante slices de acuerdo a la columna **Overall** para clasificar a los jugadores en buenos, promedios y malos.

Posteriormente, encontrar la relación de **age, international reputation, weak foot y skill moves** con que un jugador sea **good, average o bad**.

In [ ]:
good = data[torch.ge(target, 85)]
average = data[torch.lt(target, 85) & torch.gt(target, 70)]
bad = data[torch.le(target, 70)]

goodmean = torch.mean(good, dim=0)
averagemean = torch.mean(average, dim=0)
badmean = torch.mean(bad, dim=0)


for i, args in enumerate(zip(columns, goodmean, averagemean, badmean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
